[gemini]
# Gemini API配置
api_key = ""           # 在这里设置Gemini API密钥
model = "gemini-3-flash-preview"
api_url = "https://generativelanguage.googleapis.com/v1beta/models/gemini-pro-vision:generateContent"
base_url = ""  # Gemini基础URL

[chatgpt]
# ChatGPT API配置
api_key = ""  # ChatGPT API密钥
proxy_url = "https://burn.hair/v1/chat/completions"              # ChatGPT代理URL
model = "gpt-4o"
base_url = "https://burn.hair"                               # ChatGPT基础URL