[settings]
Cookie = ""
story_pic_type = "webp"

[url]
pic_driver_path = "https://cdn.jsdelivr.net/gh/{{repo}}@main/gallery/picture"
story_pic_link = "https://cdn.jsdelivr.net/gh/{{repo}}@main/template/content"
personal_page_link = "https://postcrossing.4a1801.life"

[notice]
db_update = false

[gemini]
api_key = ""
model = "gemini-3.1-flash-lite-preview"
base_url = ""
