name: 推送到Blog仓库

on:
  workflow_dispatch:
  workflow_call:

env:
  blog_path: "./src/Arthur/postcrossing"
  blog_repo: "git@github.com:arthurfsy2/arthurfsy2.github.io.git"

jobs:
  sync:
    name: 同步
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v2
        
      - name: 复制文件
        run: |
          mkdir -p "${{ env.blog_path }}"
          chmod 755 "${{ env.blog_path }}"
          cp ./output/信息汇总.md "${{ env.blog_path }}/信息汇总.md"
          echo '信息汇总.md 已复制到${{ env.blog_path }}'  
          
          cp ./gallery/sent.md "${{ env.blog_path }}/sent.md" 
          echo 'sent.md 已复制到${{ env.blog_path }}'  
        
          cp ./gallery/received.md "${{ env.blog_path }}/received.md"
          echo 'received.md 已复制到${{ env.blog_path }}'  
          
          cp ./gallery/popular.md "${{ env.blog_path }}/popular.md" 
          echo 'popular.md 已复制到${{ env.blog_path }}'
         
          cp ./gallery/favourites.md "${{ env.blog_path }}/favourites.md" 
          echo 'favourites.md 已复制到${{ env.blog_path }}'
          

      - name: 推送到博客仓库
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: ${{ env.blog_repo }}
          BRANCH: main
          FOLDER: ${{ env.blog_path }}
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          TARGET_DIR: ${{ env.blog_path }}
          MESSAGE: "已更新/src/Arthur/Postcrossing文件"
          SKIP_EMPTY_COMMITS: true
          CLEAR_GLOBS_FILE: "scripts/.clear-target-files"

      
      - name: 删除缓存文件
        run: rm -rf ${{ env.blog_path }}