name: 刷新 Cookie和邮件回复数据

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */4 * * *'
  push:
    branches:
      - main

env:
  GITHUB_NAME: arthurfsy2
  GITHUB_EMAIL: fsyflh@gmail.com
  changes: false
jobs:
  sync:
    name: 同步
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: 设置Python版本
        id: setup_python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: pip
          cache-dependency-path: 'requirements.txt'
      
      - name: 安装依赖
        run: |
          pip install -r requirements.txt
      
      - name: 检查Cookies
        run: |
          python scripts/login.py ${{ secrets.ACCOUNT }} ${{ secrets.PASSWORD }} ${{ secrets.NICKNAME }} $GITHUB_REPOSITORY
          python scripts/mailTrack.py ${{ secrets.PARMS }} ${{ secrets.APIKEY }}
    
      - name: 删除缓存文件
        run: rm -rf scripts/__pycache__/    
      
      - name: 检查文件更新
        id: check_changes
        run: |
          git diff --quiet || echo "changes=true" >> $GITHUB_OUTPUT

      - name: 提交
        run: |
          git config --local user.email "${{ env.GITHUB_EMAIL }}"
          git config --local user.name "${{ env.GITHUB_NAME }}"
          git add .
          git diff --cached --quiet || git commit -m "已更新Cookie"
          if [[ "${{ steps.check_changes.outputs.changes }}" == "true" ]]; then
            git push
          else
            echo "No changes to push."
            git reset --hard HEAD  # 取消已经提交的文件变动
          fi