name: 定时检测更新

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */1 * * *'
  push:
    branches:
      - main

env:
  GITHUB_NAME: arthurfsy2
  GITHUB_EMAIL: fsyflh@gmail.com
  blog_path: "src/Arthur/postcrossing"
  blog_repo: "git@github.com:arthurfsy2/Postcrossing_map_generator.git"

jobs:
  sync:
    name: 同步
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: 设置Python版本
        id: setup_python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: pip
          cache-dependency-path: 'requirements.txt'
      
      - name: 安装依赖
        run: |
          pip install -r requirements.txt
      
      
      - name: 安装openpyxl
        run: |
          pip install openpyxl -i http://pypi.doubanio.com/simple/ --trusted-host pypi.doubanio.com

      - name: 更新邮件回复
        run: |
          python scripts/mailTrack.py ${{ secrets.PARMS }} ${{ secrets.APIKEY }}
      
      - name: 运行startTask.py脚本
        run: |
          python scripts/startTask.py ${{ secrets.ACCOUNT }} ${{ secrets.PASSWORD }} ${{ secrets.NICKNAME }} $GITHUB_REPOSITORY
    
      - name: 删除缓存文件
        run: rm -rf scripts/__pycache__/    
      
      - name: 提交
        run: |
          git config --local user.email "${{ env.GITHUB_EMAIL }}"
          git config --local user.name "${{ env.GITHUB_NAME }}"
          git add .
          git commit -m '已更新数据' || echo "nothing to commit"
          git push || echo "nothing to push"

      - name: 推送到博客仓库
        run: |
          git config --global user.name "${{ env.GITHUB_EMAIL }}"
          git config --global user.email "${{ env.GITHUB_NAME }}"
          git remote add destination ${{ env.blog_repo }}
          git fetch origin
          git fetch destination
          git checkout -b main
          mkdir -p "${{ env.blog_path }}"
          chmod 755 "${{ env.blog_path }}"
          if [ -f output/信息汇总.md ]; then
            cp output/信息汇总.md "${{ env.blog_path }}/信息汇总.md"
            git add "${{ env.blog_path }}/信息汇总.md"  
          else
            echo '信息汇总.md 无更新'
          fi
      
          if [ -f gallery/sent.md ]; then
            cp gallery/sent.md "${{ env.blog_path }}/sent.md" 
            git add "${{ env.blog_path }}/sent.md"  
          else
            echo 'sent.md 无更新'
          fi
      
          if [ -f gallery/received.md ]; then
            cp gallery/received.md "${{ env.blog_path }}/received.md" 
            git add "${{ env.blog_path }}/received.md"  
          else
            echo 'received.md 无更新'
          fi
      
          if [ -f gallery/popular.md ]; then
            cp gallery/popular.md "${{ env.blog_path }}/popular.md" 
            git add "${{ env.blog_path }}/popular.md"  
          else
            echo 'popular.md 无更新'
          fi
      
          if [ -f gallery/favourites.md ]; then
            cp gallery/favourites.md "${{ env.blog_path }}/favourites.md" 
            git add "${{ env.blog_path }}/favourites.md"  
          else
            echo 'favourites.md 无更新'
          fi
      
          git commit -m '已push到博客仓库' || echo 'nothing to commit'
          git push destination main  || echo 'nothing to push' # 推送修改到目标仓库
          rm -rf ${{ env.blog_path }}
        env:
          TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        
