name: 定时检测更新

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */1 * * *'
  push:
    branches:
      - main

env:
  GITHUB_NAME: arthurfsy2
  GITHUB_EMAIL: fsyflh@gmail.com
  blog_path: "./src/Arthur/postcrossing"
  blog_repo: "git@github.com:arthurfsy2/arthurfsy2.github.io.git"
  PUSH_TO_GITHUB: true

jobs:
  sync:
    name: 同步
    runs-on: ubuntu-latest
    outputs:
      PUSH_TO_GITHUB: ${{ steps.push.outputs.PUSH_TO_GITHUB }}
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: 设置Python版本
        id: setup_python
        uses: actions/setup-python@main
        with:
          python-version: "3.11"
          cache: pip
          cache-dependency-path: 'requirements.txt'
      
      - name: 安装依赖
        run: |
          pip install -r requirements.txt
      
      
      - name: 安装openpyxl
        run: |
          pip install openpyxl -i http://pypi.doubanio.com/simple/ --trusted-host pypi.doubanio.com

      - name: 更新邮件回复
        run: |
          python scripts/mailTrack.py ${{ secrets.PARMS }} ${{ secrets.APIKEY }}
      
      - name: 运行startTask.py脚本
        run: |
          python scripts/startTask.py ${{ secrets.ACCOUNT }} ${{ secrets.PASSWORD }} ${{ secrets.NICKNAME }} $GITHUB_REPOSITORY ${{ secrets.APIKEY }}
    
      - name: 删除缓存文件
        run: rm -rf scripts/__pycache__/    
      
      - name: 提交
        id: push
        run: |
          git config --local user.email "${{ env.GITHUB_EMAIL }}"
          git config --local user.name "${{ env.GITHUB_NAME }}"
          git add .
          git commit -m '已更新数据' || (echo "nothing to commit" && echo "PUSH_TO_GITHUB=false" >> "$GITHUB_OUTPUT")
          git push || echo "nothing to push"
          echo "PUSH_TO_GITHUB=$PUSH_TO_GITHUB"

      - name: 复制文件
        run: |
          mkdir -p "${{ env.blog_path }}"
          chmod 755 "${{ env.blog_path }}"
          cp ./gallery/信息汇总.md "${{ env.blog_path }}/信息汇总.md"
          echo '信息汇总.md 已复制到${{ env.blog_path }}'  
          
          cp ./gallery/sent.md "${{ env.blog_path }}/sent.md" 
          echo 'sent.md 已复制到${{ env.blog_path }}'  
         
          cp ./gallery/received.md "${{ env.blog_path }}/received.md"
          echo 'received.md 已复制到${{ env.blog_path }}'  
          
          cp ./gallery/popular.md "${{ env.blog_path }}/popular.md" 
          echo 'popular.md 已复制到${{ env.blog_path }}'
         
          cp ./gallery/favourites.md "${{ env.blog_path }}/favourites.md" 
          echo 'favourites.md 已复制到${{ env.blog_path }}'

          cp ./gallery/年度报告.md "${{ env.blog_path }}/年度报告.md" 
          echo '年度报告.md 已复制到${{ env.blog_path }}'
          

      - name: 推送到博客仓库
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: ${{ env.blog_repo }}
          BRANCH: main
          FOLDER: ${{ env.blog_path }}
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          TARGET_DIR: ${{ env.blog_path }}
          MESSAGE: "已更新/src/Arthur/Postcrossing文件"
          SKIP_EMPTY_COMMITS: true
          CLEAR_GLOBS_FILE: "scripts/.clear-target-files"

      
      - name: 删除缓存文件
        run: rm -rf ${{ env.blog_path }}