name: 定时检测更新

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */1 * * *'
  push:
    branches:
      - main

env:
  GITHUB_NAME: arthurfsy2
  GITHUB_EMAIL: fsyflh@gmail.com
  blog_path: "./src/Arthur/postcrossing"
  blog_repo: "git@github.com:arthurfsy2/arthurfsy2.github.io.git"
  PUSH_TO_GITHUB: true

jobs:
  sync:
    name: 同步
    runs-on: ubuntu-latest
    outputs:
      PUSH_TO_GITHUB: ${{ steps.push.outputs.PUSH_TO_GITHUB }}
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Set Node.js max memory limit
        run: node --max-old-space-size=4096
      - name: 设置Python版本
        id: setup_python
        uses: actions/setup-python@main
        with:
          python-version: "3.11"
          cache: pip
          cache-dependency-path: 'requirements.txt'
      
      # - name: 安装依赖
      #   run: |
      #     pip install -r requirements.txt
      
      # - name: 更新邮件回复
      #   run: |
      #     python scripts/mailTrack.py ${{ secrets.PARMS }} ${{ secrets.APIKEY }}
      
      # - name: 运行startTask.py脚本
      #   run: |
      #     python scripts/startTask.py ${{ secrets.ACCOUNT }} ${{ secrets.PASSWORD }} ${{ secrets.NICKNAME }} $GITHUB_REPOSITORY ${{ secrets.APIKEY }}
    
      # - name: 删除缓存文件
      #   run: rm -rf scripts/__pycache__/    
      
      - name: 提交
        id: push
        run: |
          git config --local user.email "${{ env.GITHUB_EMAIL }}"
          git config --local user.name "${{ env.GITHUB_NAME }}"
          git add .
          git commit -m '已更新数据' || (echo "nothing to commit" && echo "PUSH_TO_GITHUB=false" >> "$GITHUB_OUTPUT")
          git push || echo "nothing to push"
          echo "PUSH_TO_GITHUB=$PUSH_TO_GITHUB"

          - name: Checkout 博客仓库
            uses: actions/checkout@main
            with:
              repository: ${{ env.blog_repo }}
              path: ${{ env.blog_repo }}
              token: ${{ secrets.GITHUB_TOKEN }}
              ref: main

          - name: 复制文件到博客仓库
            run: |
              mkdir -p "${{ env.blog_repo }}/${{ env.blog_path }}"
              cp ./gallery/* "${{ env.blog_repo }}/${{ env.blog_path }}/"
              echo "文件已复制到博客仓库"

          - name: 提交并推送到博客仓库
            run: |
              cd ${{ env.blog_repo }}
              git config --local user.email "${{ env.GITHUB_EMAIL }}"
              git config --local user.name "${{ env.GITHUB_NAME }}"
              git add .
              git commit -m "已更新/src/Arthur/Postcrossing文件" || echo "nothing to commit"
              git push || echo "nothing to push"

      - name: 删除缓存文件
        run: rm -rf ${{ env.blog_path }}

      
      - name: 删除缓存文件
        run: rm -rf ${{ env.blog_path }}