name: 定时检测更新

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */1 * * *'
  push:
    branches:
      - main

env:
  GITHUB_NAME: arthurfsy2
  GITHUB_EMAIL: fsyflh@gmail.com
  changes: false
jobs:
  sync:
    name: 同步
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: 设置Python版本
        id: setup_python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: pip
          cache-dependency-path: 'requirements.txt'
      
      - name: 安装依赖
        run: |
          pip install -r requirements.txt
      
      
      - name: 安装openpyxl
        run: |
          pip install openpyxl -i http://pypi.doubanio.com/simple/ --trusted-host pypi.doubanio.com

      - name: 更新邮件回复
        run: |
          python scripts/mailTrack.py ${{ secrets.PARMS }} ${{ secrets.APIKEY }}
      
      - name: 运行startTask.py脚本
        run: |
          python scripts/startTask.py ${{ secrets.ACCOUNT }} ${{ secrets.PASSWORD }} ${{ secrets.NICKNAME }} $GITHUB_REPOSITORY
    
      - name: 删除缓存文件
        run: rm -rf scripts/__pycache__/    
      
      - name: 提交
        run: |
          git config --local user.email "${{ env.GITHUB_EMAIL }}"
          git config --local user.name "${{ env.GITHUB_NAME }}"
          git add .
          git commit -m '已更新数据' || echo "nothing to commit"
          git push || echo "nothing to push"